name: Docs Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Build and Deploy Documentation on GH pages
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
            - name: Use Node.js v16
              uses: actions/setup-node@04c56d2f954f1e4c69436aa54cfef261a018f458 # renovate: tag=v2
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
            - name: Restore CI Cache
              uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # renovate: tag=v2.1.7
              id: cache-restore
              with:
                  path: node_modules
                  key: ${{ runner.os }}-16-${{ hashFiles('**/yarn.lock') }}
            - name: Install Dependencies if Cache Miss
              if: ${{ !steps.cache-restore.outputs.cache-hit }}
              run: yarn --frozen-lockfile
            - name: Build Docs
              run: yarn docs
            - name: Deploy Docs
              uses: JamesIves/github-pages-deploy-action@6ce741f5d4e01e15f9ea5ec96df1a43f522c330f # renovate: tag=4.1.7
              with:
                  branch: gh-pages # The branch the action should deploy to.
                  folder: docs # The folder the action should deploy.
