name: Docs Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Build and Deploy Documentation on GH pages
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
            - name: Use Node.js v16
              uses: actions/setup-node@17f8bd926464a1afa4c6a11669539e9c1ba77048 # tag=v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
            - name: Restore CI Cache
              uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # renovate: tag=v2.1.7
              id: cache-restore
              with:
                  path: node_modules
                  key: ${{ runner.os }}-16-${{ hashFiles('**/yarn.lock') }}
            - name: Install Dependencies if Cache Miss
              if: ${{ !steps.cache-restore.outputs.cache-hit }}
              run: yarn --immutable
            - name: Build Docs
              run: yarn docs
            - name: Deploy Docs
              uses: JamesIves/github-pages-deploy-action@830e6a4f7c81743c52f3fed0ac67428feff9620a # tag=v4.2.5
              with:
                  branch: gh-pages # The branch the action should deploy to.
                  folder: docs # The folder the action should deploy.
